use_frameworks!

target 'bumper_Example' do
  pod 'bumper', :path => '../'

  target 'bumper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end

post_install do | installer |
    # TODO: Should be erased in the future
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
